### ISSUE TITLE
move websites to www_archive

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_archive#1]
- [x] enertia.tech https://github.com/enertia-io/www_enertia_tech
- [x] enertia.io https://github.com/enertia-io/www_enertia_io
- [x]  euroflow https://github.com/euroflow-io/www_euroflow_io
- [x]  goldflow https://github.com/goldflow-io/www_goldflow_io
- [x]  climate_action_project 
- [x]  midori https://github.com/Incubaid/www_midori
- [x]  greenboats https://github.com/Incubaid/www_greenboats
- [x]  inid https://github.com/threefoldtech/www_inid.io
- [x] earthproject https://github.com/freeflowtribe/www_earthproject
- [x] freeflow matchmakers https://github.com/freeflownation/www_freeflowmatchmakers
- [x] cultivo https://github.com/cultivo/www_cultivo_earth
- [x] atwg.green https://github.com/atwgreen/www_atwg_tech
- [x] openly https://github.com/openlylive/www_openly_live
- [ ] faircoffee 
- [x] freeflowevent https://github.com/freeflowtribe/www_freeflowevent
- [ ] harvested https://github.com/harvested-io/www_harvested.io
- [x] https://github.com/threefoldtech/website_example 

what to do for each

- copy all relevant content to a subdir in this repo (make sure we don't loose content)
- remove the old repo once copied properly
- put new link in the overview doc
- any sites which are gridsome or mobirise publish website to html dir in the project, so we can just with browser open the site and see result
- make readme in each folder, to link to right locations & have minimal info like how created, status, where to see
- use gitpages to show the html folders so people can see using github allone

**Comment by despiegk** [comment]
sasha writing; 
- [x] - [ ] go to websites old repo, for example www_enertia
- [x] go to www_archive
- [x] make new repo : for example: enertia_archive
- [ ] copy all subfolders of www_enertia to www_archive/enertia_archive
- [x] add the new github repo link to 'Github repo' column of our overview document: https://docs.google.com/spreadsheets/d/1RsCcmXt2ds4wWK-Tdp6KokyoGl-dEW96W84O89eiE4U/edit#gid=0
- [x] use gitpages to show the html folders so people can see using github allone
- [ ] - so to be save, also download zip and upload it to our archive drive https://drive.google.com/drive/u/2/folders/1jj6utH_0jMV65p3iG4rU9iKW_gTGKr_3

@remrekoc @samaradel @ehab-hassan divide tasks between you 3 equally

**Comment by sasha-astiadi** [comment]
@ehab-hassan 

- [x]  greenboats https://github.com/Incubaid/www_greenboats
- [x]  inid https://github.com/threefoldtech/www_inid.io
- [x] earthproject https://github.com/freeflowtribe/www_earthproject
- [x] freeflow matchmakers https://github.com/freeflownation/www_freeflowmatchmakers
- [x] cultivo https://github.com/cultivo/www_cultivo_earth
- [x] - [ ] make sure new links to new github repos are updated on the excel sheet

**Comment by sasha-astiadi** [comment]
@remrekoc 
- [x] enertia.tech https://github.com/enertia-io/www_enertia_tech
- [x] enertia.io https://github.com/enertia-io/www_enertia_io
- [x]  euroflow https://github.com/euroflow-io/www_euroflow_io
- [x]  goldflow https://github.com/goldflow-io/www_goldflow_io
- [x]  midori https://github.com/Incubaid/www_midori
- [x] make sure new links to new github repos are updated on the excel sheet

**Comment by sasha-astiadi** [comment]
@samaradel 

- [x] atwg.green https://github.com/atwgreen/www_atwg_tech
- [x] openly https://github.com/openlylive/www_openly_live
- [x] freeflowevent https://github.com/freeflowtribe/www_freeflowevent
- [x] harvested https://github.com/harvested-io/www_harvested.io
- [x] https://github.com/threefoldtech/website_example 

@ehab-hassan @remrekoc please teach samar how to do it

- [x] make sure new links to new github repos are updated on the excel sheet

**Comment by samaradel** [comment]
@sasha-astiadi got it, Thanks :)

**Comment by ehab-hassan** [comment]
@sasha-astiadi @despiegk  we need admin access here so we can  use gitpages

**Comment by sasha-astiadi** [comment]
@ehab-hassan @samaradel @remrekoc 

i just made u admin on threefoldfoundation.

now you can turn everything into github pages

@remrekoc 

- [x] enertia.tech https://github.com/enertia-io/www_enertia_tech
- [x] enertia.io https://github.com/enertia-io/www_enertia_io
- [x]  euroflow https://github.com/euroflow-io/www_euroflow_io
- [x]  goldflow https://github.com/goldflow-io/www_goldflow_io
- [x]  climate_action_project 
- [x]  midori https://github.com/Incubaid/www_midori

@ehab-hassan 
- [x]  greenboats https://github.com/Incubaid/www_greenboats
- [x]  inid https://github.com/threefoldtech/www_inid.io
- [x] earthproject https://github.com/freeflowtribe/www_earthproject
- [x] freeflow matchmakers https://github.com/freeflownation/www_freeflowmatchmakers
- [x] cultivo https://github.com/cultivo/www_cultivo_earth

@samaradel 
- [x] atwg.green https://github.com/atwgreen/www_atwg_tech
- [x] openly https://github.com/openlylive/www_openly_live
- [x] freeflowevent https://github.com/freeflowtribe/www_freeflowevent
- [x] harvested https://github.com/harvested-io/www_harvested.io
- [] https://github.com/threefoldtech/website_example

**Comment by ehab-hassan** [comment]
I tried to do GitHub pages but it seems that can be done for just one website at repo not all website because the preview done from one index.html

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_archive

all github pages are live

**Comment by sasha-astiadi** [comment]
https://threefoldfoundation.github.io/www_archive/enertia_tech_archive/ didnt deploy on github pages because its done using php ( WordPress )

**Comment by sasha-astiadi** [comment]
https://threefoldfoundation.github.io/www_archive/greenboats_archive/ not working @remrekoc @ehab-hassan pleaase check what framework being used

**Comment by sasha-astiadi** [comment]
https://threefoldfoundation.github.io/www_archive/midori_archive/ github pages not working. using hugo

**Comment by sasha-astiadi** [comment]
everything moved already to https://github.com/threefoldfoundation/www_archive and google drive. i will start archiving / deleting the old repos .

- [x] enertia.tech https://github.com/enertia-io/www_enertia_tech
- [ ] enertia.io https://github.com/enertia-io/www_enertia_io
- [ ]  euroflow https://github.com/euroflow-io/www_euroflow_io
- [ ]  goldflow https://github.com/goldflow-io/www_goldflow_io
- [x]  climate_action_project 
- [x]  midori https://github.com/Incubaid/www_midori
- [x]  greenboats https://github.com/Incubaid/www_greenboats
- [x]  inid https://github.com/threefoldtech/www_inid.io
- [x] earthproject https://github.com/freeflowtribe/www_earthproject
- [x] freeflow matchmakers https://github.com/freeflownation/www_freeflowmatchmakers
- [x] cultivo https://github.com/cultivo/www_cultivo_earth
- [ ] atwg.green https://github.com/atwgreen/www_atwg_tech
- [ ] openly https://github.com/openlylive/www_openly_live
- [x] freeflowevent https://github.com/freeflowtribe/www_freeflowevent
- [ ] harvested https://github.com/harvested-io/www_harvested.io
- [x]  https://github.com/threefoldtech/website_example
 

please check gdrive and www_archive

make sure all copies are there.

**Comment by ehab-hassan** [comment]
@sasha-astiadi I checked all on drive and www_archive  except climate_action_project where is repoo for this?

**Comment by remrekoc** [comment]
I checked all archive folders on github and drive. Move to www_archive is complete. We only need to fix the couple broken github pages links. We can delete old repos that are already moved. @ehab-hassan @sasha-astiadi

**Comment by sasha-astiadi** [comment]
3 blocking undeployable repos, issue here:

[find a way to deploy some www_archive websites](https://github.com/threefoldfoundation/www_archive/issues/6)

**Comment by sasha-astiadi** [comment]
the only ones not deleted yet:

 enertia.io https://github.com/enertia-io/www_enertia_io
 euroflow https://github.com/euroflow-io/www_euroflow_io
 goldflow https://github.com/goldflow-io/www_goldflow_io
 faircoffe
 harvested https://github.com/harvested-io/www_harvested.io



need admin access from kds to delete
will close this one for others, and open new issue for the above problem, see https://github.com/threefoldfoundation/www_archive/issues/7

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_archive/issues/7

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldfoundation/www_archive/issues/7
