### ISSUE TITLE
build climate project github pages using gridsome

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_archive#10]
clone to org incubaid_archive

- [x] climate - gridsome

- [x] build climate github pages @ehab-hassan

**Comment by ehab-hassan** [comment]
@sasha-astiadi Climate had a lot of errors when trying to run, I dont know if that go online before I think fixing the errors and try to run at Github pages ll waste time.

**Comment by ehab-hassan** [comment]
there is no data it just template website
GitHub page :
https://incubaid-archive.github.io/climate_archive/
repo :
https://github.com/incubaid-archive/climate_archive
