### ISSUE TITLE
improve web presence list

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_archive#2]
- [x]  put link in readme to https://docs.google.com/spreadsheets/d/1RsCcmXt2ds4wWK-Tdp6KokyoGl-dEW96W84O89eiE4U/edit#gid=0

- [x] make sure github repo;s are filled in, lots missing

- [x] gitea repo doesn't seem to be right, its how the IT system is deployed, make distinction between IT deployment & where source code is

**Comment by sasha-astiadi** [comment]
- changed gitea repo to IT Info Gitea
- link added to TFFoundation org read.me
- links will be updated once old repos are renewed / archived in the right repos and in the right organizations
