### ISSUE TITLE
get www.3bot in this repo

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_archive#4]
https://github.com/threefoldtech/www_3bot_org_archive

see what we had to do for others, github pages, publish...
remove repo from source

**Comment by sasha-astiadi** [comment]
- [x] move to www_archive @ehab-hassan 
- [x] build github pages @ehab-hassan

**Comment by ehab-hassan** [comment]
repo moved to www.archive and drive 
https://github.com/threefoldfoundation/www_archive/tree/main/3bot_org_archive
Github page https://threefoldfoundation.github.io/www_archive/3bot_org_archive/
