### ISSUE TITLE
fix old accounts

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_archive#5]
## Nothing to do

- [x] [BetterToken](https://github.com/BetterToken) owner
- [x] [freeflowuniverse](https://github.com/freeflowuniverse) freeflowuniverse owner
- [x] [Incubaid](https://github.com/Incubaid) Incubaid owner
- [x] [incubaid-archive](https://github.com/incubaid-archive) incubaid-archive owner
- [x] [threefoldtech](https://github.com/threefoldtech) threefoldtech owner
- [x] [threefoldfoundation](https://github.com/threefoldfoundation) threefoldfoundation owner
- [x] [rivine](https://github.com/rivine) rivine owner
- [x] [g8os](https://github.com/g8os) g8os owner
- [x] [gig-archive](https://github.com/gig-archive) gig-archive owner
- [x] [openvstorage](https://github.com/openvstorage) openvstorage owner
- [x] [ourworld-tsc](https://github.com/ourworld-tsc) ourworld-tsc owner

## move to incubaid-archive, archive all repo's

- [ ] [CARBEXC](https://github.com/CARBEXC) CARBEXC owner  
- [x] [crystal-home](https://github.com/crystal-home) crystal-home owner
- [x] [cultivo](https://github.com/cultivo) cultivo owner
- [x] [digitalyouonline](https://github.com/digitalyouonline) digitalyouonline owner
- [x] [enertia-io](https://github.com/enertia-io) enertia-io owner
- [x] [itsyouonline](https://github.com/itsyouonline) itsyouonline owner
- [x] [Jumpscale](https://github.com/Jumpscale) Jumpscale owner
- [x] [Jumpscale-Cockpit](https://github.com/Jumpscale-Cockpit) Jumpscale-Cockpit owner
- [x] [jumpscale7](https://github.com/jumpscale7) jumpscale7 owner
- [x] [mitaa-me](https://github.com/mitaa-me) mitaa-me owner
- [x] [nimscale](https://github.com/nimscale) nimscale owner
- [ ] [nodescale](https://github.com/nodescale) nodescale owner
- [x] [omni-sphere](https://github.com/omni-sphere) omni-sphere owner
- [x] [ourcommunityapp](https://github.com/ourcommunityapp) ourcommunityapp owner (has no repo)
- [x] [threebotapps](https://github.com/threebotapps) threebotapps owner
- [ ] [threebotserver](https://github.com/threebotserver) threebotserver owner (has no repo)
- [ ] [zero-os-no-longer-used](https://github.com/zero-os-no-longer-used) zero-os-no-longer-used owner
- [ ] [uyazi](https://github.com/uyazi) uyazi owner

remove the account afterwards, make sure we have all
do not download zip of the repos but clone instead to make sure we do not lose history and branches

## Others / sasha

see if we can use script https://github.com/jdbean/github-api-bulk-transfer to transfer multiple repos at once to new org?

- [x] [gigforks](https://github.com/gigforks) gigforks owner
  - move to gig-archive & archive
- [x] [freeflowpages](https://github.com/freeflowpages) freeflowpages owner
  - move to freeflowuniverse
- [x] [freeflowtribe](https://github.com/freeflowtribe) freeflowtribe owner
  - move to freeflowuniverse
- [x] [myfreeflow](https://github.com/myfreeflow) myfreeflow owner
  - move to freeflowuniverse
  - see if anything relevant in home, otherwise remove
- [x] [takeactionglobal](https://github.com/takeactionglobal) owner
  - see if relevant in home

sasha
  - move to ourworld-tsc
- [x] [threefoldgrid](https://github.com/threefoldgrid) threefoldgrid owner
  - see what is relevant move to threefold_foundation, archive if needed, remove rest
- [ ] [threefoldtoken](https://github.com/threefoldtoken) threefoldtoken owner
  - see what is relevant move to threefold_foundation, archive if needed, remove rest
- [x] [uhuru-me](https://github.com/uhuru-me) uhuru-me owner
  - move to freeflowuniverse
- [x] [veda-online](https://github.com/veda-online) veda-online owner
  - move to ourworld-tsc
- [x] [veda-university](https://github.com/veda-university) veda-university owner
  - move to ourworld-tsc
- [x] [veda-websites](https://github.com/veda-websites) veda-websites owner
  - move to ourworld-tsc
  
  ## remark

  - for everything we delete, do not download zip of the repos but clone instead to make sure we do not lose history and branches
  - put the zips on googdrive : https://drive.google.com/drive/folders/1jj6utH_0jMV65p3iG4rU9iKW_gTGKr_3

**Comment by sasha-astiadi** [comment]
please give me access to your github acc . at leasr give me access to all the orgs @despiegk

**Comment by sasha-astiadi** [comment]
@ehab-hassan do the first 9, @remrekoc do the last 9

**Comment by sasha-astiadi** [comment]
- [x] go to respective repo
- [ ] clone the repo
- [x] add _archive on the folder name
- [ ] upload zipped folder to [drive ](https://drive.google.com/drive/u/2/folders/1jj6utH_0jMV65p3iG4rU9iKW_gTGKr_3)
- [x] no need to upload to incubaid_archive

**Comment by despiegk** [comment]
sasha to kds: suggest not to move [threefoldtoken](https://github.com/threefoldtoken) threefoldtoken owner

because it contains legal folder, it will break many legal links on our products and services @despiegk

**Comment by despiegk** [comment]
@ehab-hassan @remrekoc when you update and archived them, please make sure the links are updated on the excel sheet thank you

**Comment by sasha-astiadi** [comment]
you guys moved these repos to the wrong org

## move to **incubaid-archive**, archive all repo's

- [ ] [CARBEXC](https://github.com/CARBEXC) CARBEXC owner  
- [x] [crystal-home](https://github.com/crystal-home) crystal-home owner
- [x] [cultivo](https://github.com/cultivo) cultivo owner
- [x] [digitalyouonline](https://github.com/digitalyouonline) digitalyouonline owner
- [x] [enertia-io](https://github.com/enertia-io) enertia-io owner
- [x] [itsyouonline](https://github.com/itsyouonline) itsyouonline owner
- [x] [Jumpscale](https://github.com/Jumpscale) Jumpscale owner
- [ ] [Jumpscale-Cockpit](https://github.com/Jumpscale-Cockpit) Jumpscale-Cockpit owner
- [x] [jumpscale7](https://github.com/jumpscale7) jumpscale7 owner
- [x] [mitaa-me](https://github.com/mitaa-me) mitaa-me owner
- [ ] [nimscale](https://github.com/nimscale) nimscale owner
- [x] [nodescale](https://github.com/nodescale) nodescale owner
- [ ] [omni-sphere](https://github.com/omni-sphere) omni-sphere owner
- [x] [ourcommunityapp](https://github.com/ourcommunityapp) ourcommunityapp owner (has no repo)
- [x] [threebotapps](https://github.com/threebotapps) threebotapps owner
- [x] [threebotserver](https://github.com/threebotserver) threebotserver owner (has no repo)
- [x] [zero-os-no-longer-used](https://github.com/zero-os-no-longer-used) zero-os-no-longer-used owner
- [x] [uyazi](https://github.com/uyazi) uyazi owner


delete tjose from www_archive

- [ ] [CARBEXC](https://github.com/CARBEXC) CARBEXC owner  
- [x] [crystal-home](https://github.com/crystal-home) crystal-home owner
- [ ] [cultivo](https://github.com/cultivo) cultivo owner
- [ ] [digitalyouonline](https://github.com/digitalyouonline) digitalyouonline owner
- [ ] [enertia-io](https://github.com/enertia-io) enertia-io owner
- [ ] [itsyouonline](https://github.com/itsyouonline) itsyouonline owner
- [ ] [Jumpscale](https://github.com/Jumpscale) Jumpscale owner
- [ ] [Jumpscale-Cockpit](https://github.com/Jumpscale-Cockpit) Jumpscale-Cockpit owner
- [ ] [jumpscale7](https://github.com/jumpscale7) jumpscale7 owner
- [ ] [mitaa-me](https://github.com/mitaa-me) mitaa-me owner
- [x] [nimscale](https://github.com/nimscale) nimscale owner
- [ ] [nodescale](https://github.com/nodescale) nodescale owner
- [ ] [omni-sphere](https://github.com/omni-sphere) omni-sphere owner
- [x] [ourcommunityapp](https://github.com/ourcommunityapp) ourcommunityapp owner (has no repo)
- [x] [threebotapps](https://github.com/threebotapps) threebotapps owner
- [x] [threebotserver](https://github.com/threebotserver) threebotserver owner (has no repo)
- [x] [zero-os-no-longer-used](https://github.com/zero-os-no-longer-used) zero-os-no-longer-used owner
- [x] [uyazi](https://github.com/uyazi) uyazi owner


it says to move them to https://github.com/incubaid-archive


let me know when moved, i will delete the old repos original
@ehab-hassan

**Comment by ehab-hassan** [comment]
@sasha-astiadi as @remrekoc inform us before that he checked with Kristof and no need to put it at  incubaid_archive  just in google drive and I checked all there except ourcommunityapp & threebotserver there is no repo.

**Comment by remrekoc** [comment]
All folders to be moved to incubaid_archive are in drive. It looks like some folders that are supposed to be moved to www_archive are moved to incubaid_archive. Let's meet tomorrow to clean up incubaid_archive so there's no confusion. Once the issue around the incubaid_archive org is solved, we can delete old repos. @ehab-hassan @sasha-astiadi

**Comment by sasha-astiadi** [comment]
@ehab-hassan see @remrekoc comment... why are you two saying two different things? so at the end we still need to move it to incubaid archive.

**Comment by sasha-astiadi** [comment]
@remrekoc let me know when you moved everything to incubaid_archive, then i will delete

**Comment by sasha-astiadi** [comment]
only  carbec not done, need access
https://github.com/orgs/threefoldfoundation/projects/80/views/1
