### ISSUE TITLE
find a way to deploy some www_archive websites

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_archive#6]
these websites are srchived and saved but eunable to deploy the github pages

- [x] greenboats
- [x] midori

we need to find a way to deploy these

https://threefoldfoundation.github.io/www_archive/enertia_tech_archive/ didnt deploy on github pages because its done using php ( WordPress )

sasha-astiadi
[4 days ago](https://github.com/threefoldfoundation/www_archive/issues/1#issuecomment-1184474748)
·
Member
https://threefoldfoundation.github.io/www_archive/greenboats_archive/ not working @remrekoc @ehab-hassan pleaase check what framework being used

sasha-astiadi
[4 days ago](https://github.com/threefoldfoundation/www_archive/issues/1#issuecomment-1184475929)
·
Member
https://threefoldfoundation.github.io/www_archive/midori_archive/

https://github.com/threefoldfoundation/www_archive/tree/main/climate_archive

**Comment by sasha-astiadi** [comment]
clone these repos from foundation/www_archive to another organization : https://github.com/incubaid-archive
put tthem in separate repo.

- [x] greenboats - hugo
- [x] midori - hugo

**Comment by ehab-hassan** [comment]
https://incubaid-archive.github.io/midori_archive/
https://incubaid-archive.github.io/greenboats_archive/
